#!/usr/bin/env python3
"""
Plot temporal evolution of spatial dispersion sigma_v(t) for different K values.

This script reads simulation outputs generated by the Java simulator,
computes sigma_v(t) per realization (spatial std over neurons), groups
realizations by K, averages across realizations, and plots one curve per K.

It also stores a compact CSV cache with only what is needed to plot:
k,time,mean_sigma_v,std_sigma_v,n_reps
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import os
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
_DEFAULT_INPUT_DIR = _PROJECT_ROOT / "Simulation" / "output"
_DEFAULT_CSV_CACHE = _PROJECT_ROOT / "Visualization" / "sigma_v_cache.csv"

_BEGIN_STATE_RE = re.compile(r"^BEGIN_STATE t=([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot sigma_v(t) grouped by K from simulation output files.",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=_DEFAULT_INPUT_DIR,
        help=f"Directory with output .txt files (default: {_DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--pattern",
        default="fhn_*.txt",
        help="Glob pattern to select files inside input dir (default: fhn_*.txt)",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Save figure to file (e.g. sigma_v_vs_time.png). If omitted, shows interactively.",
    )
    parser.add_argument(
        "--no-std-band",
        action="store_true",
        help="Disable shaded +-1 std band across realizations.",
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=_DEFAULT_CSV_CACHE,
        help=(
            "CSV cache file for aggregated sigma_v(t) data "
            f"(default: {_DEFAULT_CSV_CACHE})"
        ),
    )
    parser.add_argument(
        "--csv-mode",
        choices=["auto", "use", "recompute"],
        default="auto",
        help=(
            "Data source mode: use existing CSV, recompute from txt outputs, "
            "or auto (use CSV if exists, otherwise recompute and save)."
        ),
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=0,
        help=(
            "Threads used to parse output files when recomputing. "
            "0 = automatic (based on number of files/reps)."
        ),
    )
    parser.add_argument(
        "--k-values",
        type=float,
        nargs="+",
        default=None,
        help="Optional list of K values to include in plot and CSV.",
    )
    return parser.parse_args()


def _resolve_project_path(path: Path) -> Path:
    if path.is_absolute():
        return path
    return (_PROJECT_ROOT / path).resolve()


def _parse_file_sigma_v(path: Path) -> tuple[float, np.ndarray, np.ndarray]:
    """
    Returns
    -------
    k_value : float
    times   : np.ndarray shape (T,)
    sigma_v : np.ndarray shape (T,)
    """
    k_value: float | None = None
    times: list[float] = []
    sigma_v: list[float] = []
    current_t: float | None = None

    with path.open("r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue

            if line.startswith("K="):
                k_value = float(line.split("=", 1)[1])
                continue

            match = _BEGIN_STATE_RE.match(line)
            if match:
                current_t = float(match.group(1))
                continue

            if line.startswith("v ") and current_t is not None:
                v_vals = np.fromstring(line[2:], sep=" ")
                if v_vals.size == 0:
                    raise ValueError(f"Could not parse v values in {path}")
                times.append(current_t)
                sigma_v.append(float(v_vals.std()))
                current_t = None

    if k_value is None:
        raise ValueError(f"K not found in header: {path}")
    if not times:
        raise ValueError(f"No states found in file: {path}")

    return k_value, np.asarray(times), np.asarray(sigma_v)


def _align_series(series: list[tuple[np.ndarray, np.ndarray]], k_value: float) -> tuple[np.ndarray, np.ndarray]:
    lengths = [len(t) for t, _ in series]
    min_len = min(lengths)

    if len(set(lengths)) > 1:
        print(
            f"Warning: K={k_value:g} has different trajectory lengths {sorted(set(lengths))}. "
            f"Truncating to {min_len}."
        )

    times_ref = series[0][0][:min_len]
    stacked = np.vstack([vals[:min_len] for _, vals in series])
    return times_ref, stacked


def _summarize_by_k(
    by_k: dict[float, list[tuple[np.ndarray, np.ndarray]]]
) -> dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]]:
    summary: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]] = {}
    for k_value in sorted(by_k):
        times_ref, values = _align_series(by_k[k_value], k_value)
        mean_curve = values.mean(axis=0)
        std_curve = values.std(axis=0)
        n_reps = int(values.shape[0])
        summary[k_value] = (times_ref, mean_curve, std_curve, n_reps)
    return summary


def _save_csv_cache(
    summary_by_k: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]],
    csv_path: Path,
) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)

    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["k", "time", "mean_sigma_v", "std_sigma_v", "n_reps"])

        for k_value in sorted(summary_by_k):
            times, mean_sigma, std_sigma, n_reps = summary_by_k[k_value]
            for t, m, s in zip(times, mean_sigma, std_sigma):
                writer.writerow([
                    f"{k_value:.17g}",
                    f"{float(t):.17g}",
                    f"{float(m):.17g}",
                    f"{float(s):.17g}",
                    str(n_reps),
                ])


def _load_csv_cache(csv_path: Path) -> dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]]:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV cache not found: {csv_path}")

    with csv_path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        fields = set(reader.fieldnames or [])
        expected = {"k", "time", "mean_sigma_v", "std_sigma_v", "n_reps"}
        if not expected.issubset(fields):
            raise ValueError(
                "CSV format not recognized. Expected columns "
                "[k,time,mean_sigma_v,std_sigma_v,n_reps]."
            )

        grouped: dict[float, tuple[list[float], list[float], list[float], int]] = {}
        for row in reader:
            k_value = float(row["k"])
            t_val = float(row["time"])
            mean_val = float(row["mean_sigma_v"])
            std_val = float(row["std_sigma_v"])
            n_reps = int(row["n_reps"])

            if k_value not in grouped:
                grouped[k_value] = ([], [], [], n_reps)

            grouped[k_value][0].append(t_val)
            grouped[k_value][1].append(mean_val)
            grouped[k_value][2].append(std_val)

    summary: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]] = {}
    for k_value, (times, means, stds, n_reps) in grouped.items():
        summary[k_value] = (
            np.asarray(times),
            np.asarray(means),
            np.asarray(stds),
            n_reps,
        )
    return summary


def _build_data_from_outputs(
    input_dir: Path,
    pattern: str,
    threads: int,
) -> tuple[dict[float, list[tuple[np.ndarray, np.ndarray]]], int, int]:
    if not input_dir.exists():
        raise SystemExit(f"Input directory not found: {input_dir}")

    files = sorted(input_dir.glob(pattern))
    if not files:
        raise SystemExit(f"No files matched pattern '{pattern}' in {input_dir}")

    cpu_count = os.cpu_count() or 1
    if threads == 0:
        max_workers = min(len(files), cpu_count)
    else:
        if threads < 1:
            raise SystemExit("--threads must be >= 1 (or 0 for auto)")
        max_workers = min(threads, len(files))

    print(f"Recompute mode parsing with {max_workers} thread(s) over {len(files)} file(s)")

    by_k: dict[float, list[tuple[np.ndarray, np.ndarray]]] = {}
    parsed = 0
    skipped = 0

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_file = {executor.submit(_parse_file_sigma_v, file_path): file_path for file_path in files}
        for future in concurrent.futures.as_completed(future_to_file):
            file_path = future_to_file[future]
            try:
                k_value, times, sigma_v = future.result()
            except Exception as exc:  # noqa: BLE001 - continue with remaining files
                skipped += 1
                print(f"Skipping {file_path.name}: {exc}")
                continue

            by_k.setdefault(k_value, []).append((times, sigma_v))
            parsed += 1

    if not by_k:
        raise SystemExit("No valid simulation files were parsed.")

    return by_k, parsed, skipped


def _filter_summary_by_k(
    summary_by_k: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]],
    selected_k: list[float] | None,
) -> dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]]:
    if not selected_k:
        return summary_by_k

    selected = {float(k) for k in selected_k}
    filtered = {k: v for k, v in summary_by_k.items() if float(k) in selected}
    if not filtered:
        raise SystemExit(
            "No K values matched --k-values. "
            f"Available K in data: {', '.join(format(k, 'g') for k in sorted(summary_by_k))}"
        )
    return filtered


def main() -> None:
    args = parse_args()

    csv_path = _resolve_project_path(args.csv)
    input_dir = _resolve_project_path(args.input_dir)

    if args.csv_mode == "use":
        summary_by_k = _load_csv_cache(csv_path)
        summary_by_k = _filter_summary_by_k(summary_by_k, args.k_values)
        parsed = sum(data[3] for data in summary_by_k.values())
        skipped = 0
        print(f"Using existing CSV cache: {csv_path}")
    elif args.csv_mode == "recompute":
        by_k, parsed, skipped = _build_data_from_outputs(input_dir, args.pattern, args.threads)
        summary_by_k = _summarize_by_k(by_k)
        summary_by_k = _filter_summary_by_k(summary_by_k, args.k_values)
        _save_csv_cache(summary_by_k, csv_path)
        print(f"Recomputed data and saved CSV cache: {csv_path}")
    else:
        if csv_path.exists():
            summary_by_k = _load_csv_cache(csv_path)
            summary_by_k = _filter_summary_by_k(summary_by_k, args.k_values)
            parsed = sum(data[3] for data in summary_by_k.values())
            skipped = 0
            print(f"Auto mode: using existing CSV cache {csv_path}")
        else:
            by_k, parsed, skipped = _build_data_from_outputs(input_dir, args.pattern, args.threads)
            summary_by_k = _summarize_by_k(by_k)
            summary_by_k = _filter_summary_by_k(summary_by_k, args.k_values)
            _save_csv_cache(summary_by_k, csv_path)
            print(f"Auto mode: CSV cache created at {csv_path}")

    print(f"Parsed files: {parsed} (skipped: {skipped})")
    print(f"Detected K values: {', '.join(format(k, 'g') for k in sorted(summary_by_k))}")

    fig, ax = plt.subplots(figsize=(10, 6))

    for k_value in sorted(summary_by_k):
        times_ref, mean_curve, std_curve, n_reps = summary_by_k[k_value]
        label = f"K={k_value:g}"

        ax.plot(times_ref, mean_curve, linewidth=2.8, label=label)
        if not args.no_std_band and n_reps > 1:
            ax.fill_between(
                times_ref,
                mean_curve - std_curve,
                mean_curve + std_curve,
                alpha=0.2,
            )

    ax.set_xlabel("Tiempo (s)", fontsize=22)
    ax.set_ylabel("Dispersión espacial σv(t)", fontsize=22)
    ax.tick_params(axis="both", labelsize=19)
    ax.grid(True, alpha=0.3)
    legend_cols = max(1, min(6, len(summary_by_k)))
    ax.legend(
        loc="lower center",
        bbox_to_anchor=(0.5, 1.02),
        ncol=legend_cols,
        borderaxespad=0.0,
        fontsize=17,
    )
    fig.tight_layout(rect=[0.0, 0.0, 1.0, 0.9])

    if args.save is not None:
        out_path = args.save
        if not out_path.is_absolute():
            out_path = _PROJECT_ROOT / out_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=150)
        print(f"Saved figure: {out_path}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
