#!/usr/bin/env python3
"""
Plot temporal evolution of mean membrane potential <v(t)> for different K values.

This script reads simulation outputs generated by the Java simulator (including
outputs produced by sweep.py), computes <v(t)> for each realization, groups
realizations by K, and plots one curve per K.

By default it also shows a shaded +-1 std band across realizations for each K.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import os
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
_DEFAULT_INPUT_DIR = _PROJECT_ROOT / "Simulation" / "output"
_DEFAULT_CSV_CACHE = _PROJECT_ROOT / "Visualization" / "mean_v_cache.csv"

_BEGIN_STATE_RE = re.compile(r"^BEGIN_STATE t=([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot <v(t)> grouped by K from simulation output files.",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=_DEFAULT_INPUT_DIR,
        help=f"Directory with output .txt files (default: {_DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--pattern",
        default="fhn_*.txt",
        help="Glob pattern to select files inside input dir (default: fhn_*.txt)",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Save figure to file (e.g. mean_v_vs_time.png). If omitted, shows interactively.",
    )
    parser.add_argument(
        "--no-std-band",
        action="store_true",
        help="Disable shaded +-1 std band across realizations.",
    )
    parser.add_argument(
        "--title",
        default="Evolucion temporal de <v(t)> por K",
        help="Figure title",
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=_DEFAULT_CSV_CACHE,
        help=(
            "CSV cache file for parsed <v(t)> data "
            f"(default: {_DEFAULT_CSV_CACHE})"
        ),
    )
    parser.add_argument(
        "--csv-mode",
        choices=["auto", "use", "recompute"],
        default="auto",
        help=(
            "Data source mode: use existing CSV, recompute from txt outputs, "
            "or auto (use CSV if exists, otherwise recompute and save)."
        ),
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=0,
        help=(
            "Threads used to parse output files when recomputing. "
            "0 = automatic (based on number of files/reps)."
        ),
    )
    return parser.parse_args()


def _resolve_project_path(path: Path) -> Path:
    if path.is_absolute():
        return path
    return (_PROJECT_ROOT / path).resolve()


def _parse_file_mean_v(path: Path) -> tuple[float, np.ndarray, np.ndarray]:
    """
    Returns
    -------
    k_value : float
    times   : np.ndarray shape (T,)
    mean_v  : np.ndarray shape (T,)
    """
    k_value: float | None = None
    times: list[float] = []
    mean_v: list[float] = []
    current_t: float | None = None

    with path.open("r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue

            if line.startswith("K="):
                k_value = float(line.split("=", 1)[1])
                continue

            match = _BEGIN_STATE_RE.match(line)
            if match:
                current_t = float(match.group(1))
                continue

            if line.startswith("v ") and current_t is not None:
                v_vals = np.fromstring(line[2:], sep=" ")
                if v_vals.size == 0:
                    raise ValueError(f"Could not parse v values in {path}")
                times.append(current_t)
                mean_v.append(float(v_vals.mean()))
                current_t = None

    if k_value is None:
        raise ValueError(f"K not found in header: {path}")
    if not times:
        raise ValueError(f"No states found in file: {path}")

    return k_value, np.asarray(times), np.asarray(mean_v)


def _align_series(series: list[tuple[np.ndarray, np.ndarray]], k_value: float) -> tuple[np.ndarray, np.ndarray]:
    """
    Align realizations for one K to a common length.

    Returns
    -------
    times_ref : np.ndarray (Tmin,)
    values    : np.ndarray (R, Tmin)
    """
    lengths = [len(t) for t, _ in series]
    min_len = min(lengths)

    if len(set(lengths)) > 1:
        print(
            f"Warning: K={k_value:g} has different trajectory lengths {sorted(set(lengths))}. "
            f"Truncating to {min_len}."
        )

    times_ref = series[0][0][:min_len]
    stacked = np.vstack([vals[:min_len] for _, vals in series])
    return times_ref, stacked


def _summarize_by_k(
    by_k: dict[float, list[tuple[np.ndarray, np.ndarray]]]
) -> dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]]:
    summary: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]] = {}
    for k_value in sorted(by_k):
        times_ref, values = _align_series(by_k[k_value], k_value)
        mean_curve = values.mean(axis=0)
        std_curve = values.std(axis=0)
        n_reps = int(values.shape[0])
        summary[k_value] = (times_ref, mean_curve, std_curve, n_reps)
    return summary


def _save_csv_cache(
    summary_by_k: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]],
    csv_path: Path,
) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)

    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["k", "time", "mean_v", "std_v", "n_reps"])

        for k_value in sorted(summary_by_k):
            times, mean_v, std_v, n_reps = summary_by_k[k_value]
            for t, m, s in zip(times, mean_v, std_v):
                writer.writerow([
                    f"{k_value:.17g}",
                    f"{float(t):.17g}",
                    f"{float(m):.17g}",
                    f"{float(s):.17g}",
                    str(n_reps),
                ])


def _load_csv_cache(csv_path: Path) -> dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]]:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV cache not found: {csv_path}")

    with csv_path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        fields = set(reader.fieldnames or [])

        # New compact cache format: one row per (K, t)
        expected_compact = {"k", "time", "mean_v", "std_v", "n_reps"}
        if expected_compact.issubset(fields):
            grouped_compact: dict[float, tuple[list[float], list[float], list[float], int]] = {}
            for row in reader:
                k_value = float(row["k"])
                t_val = float(row["time"])
                mean_val = float(row["mean_v"])
                std_val = float(row["std_v"])
                n_reps = int(row["n_reps"])

                if k_value not in grouped_compact:
                    grouped_compact[k_value] = ([], [], [], n_reps)

                grouped_compact[k_value][0].append(t_val)
                grouped_compact[k_value][1].append(mean_val)
                grouped_compact[k_value][2].append(std_val)

            summary: dict[float, tuple[np.ndarray, np.ndarray, np.ndarray, int]] = {}
            for k_value, (times, means, stds, n_reps) in grouped_compact.items():
                summary[k_value] = (
                    np.asarray(times),
                    np.asarray(means),
                    np.asarray(stds),
                    n_reps,
                )
            return summary

        # Backward compatibility with old verbose cache format.
        expected_old = {"k", "series_id", "time", "mean_v"}
        if expected_old.issubset(fields):
            grouped_old: dict[tuple[float, int], tuple[list[float], list[float]]] = {}
            for row in reader:
                k_value = float(row["k"])
                series_id = int(row["series_id"])
                t_val = float(row["time"])
                v_val = float(row["mean_v"])

                key = (k_value, series_id)
                if key not in grouped_old:
                    grouped_old[key] = ([], [])
                grouped_old[key][0].append(t_val)
                grouped_old[key][1].append(v_val)

            by_k: dict[float, list[tuple[np.ndarray, np.ndarray]]] = {}
            for (k_value, _series_id), (times, values) in grouped_old.items():
                by_k.setdefault(k_value, []).append((np.asarray(times), np.asarray(values)))
            return _summarize_by_k(by_k)

        raise ValueError(
            "CSV format not recognized. Expected compact columns "
            "[k,time,mean_v,std_v,n_reps] or legacy columns [k,series_id,time,mean_v]."
        )


def _build_data_from_outputs(
    input_dir: Path,
    pattern: str,
    threads: int,
) -> tuple[dict[float, list[tuple[np.ndarray, np.ndarray]]], int, int]:
    if not input_dir.exists():
        raise SystemExit(f"Input directory not found: {input_dir}")

    files = sorted(input_dir.glob(pattern))
    if not files:
        raise SystemExit(f"No files matched pattern '{pattern}' in {input_dir}")

    cpu_count = os.cpu_count() or 1
    if threads == 0:
        max_workers = min(len(files), cpu_count)
    else:
        if threads < 1:
            raise SystemExit("--threads must be >= 1 (or 0 for auto)")
        max_workers = min(threads, len(files))

    print(f"Recompute mode parsing with {max_workers} thread(s) over {len(files)} file(s)")

    by_k: dict[float, list[tuple[np.ndarray, np.ndarray]]] = {}
    parsed = 0
    skipped = 0

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_file = {executor.submit(_parse_file_mean_v, file_path): file_path for file_path in files}
        for future in concurrent.futures.as_completed(future_to_file):
            file_path = future_to_file[future]
            try:
                k_value, times, mean_v = future.result()
            except Exception as exc:  # noqa: BLE001 - continue with remaining files
                skipped += 1
                print(f"Skipping {file_path.name}: {exc}")
                continue

            by_k.setdefault(k_value, []).append((times, mean_v))
            parsed += 1

    if not by_k:
        raise SystemExit("No valid simulation files were parsed.")

    return by_k, parsed, skipped


def main() -> None:
    args = parse_args()

    csv_path = _resolve_project_path(args.csv)
    input_dir = _resolve_project_path(args.input_dir)

    if args.csv_mode == "use":
        summary_by_k = _load_csv_cache(csv_path)
        parsed = sum(data[3] for data in summary_by_k.values())
        skipped = 0
        print(f"Using existing CSV cache: {csv_path}")
    elif args.csv_mode == "recompute":
        by_k, parsed, skipped = _build_data_from_outputs(input_dir, args.pattern, args.threads)
        summary_by_k = _summarize_by_k(by_k)
        _save_csv_cache(summary_by_k, csv_path)
        print(f"Recomputed data and saved CSV cache: {csv_path}")
    else:
        if csv_path.exists():
            summary_by_k = _load_csv_cache(csv_path)
            parsed = sum(data[3] for data in summary_by_k.values())
            skipped = 0
            print(f"Auto mode: using existing CSV cache {csv_path}")
        else:
            by_k, parsed, skipped = _build_data_from_outputs(input_dir, args.pattern, args.threads)
            summary_by_k = _summarize_by_k(by_k)
            _save_csv_cache(summary_by_k, csv_path)
            print(f"Auto mode: CSV cache created at {csv_path}")

    print(f"Parsed files: {parsed} (skipped: {skipped})")
    print(f"Detected K values: {', '.join(format(k, 'g') for k in sorted(summary_by_k))}")

    fig, ax = plt.subplots(figsize=(10, 6))

    for k_value in sorted(summary_by_k):
        times_ref, mean_curve, std_curve, n_reps = summary_by_k[k_value]
        label = f"K={k_value:g} (n={n_reps})"

        ax.plot(times_ref, mean_curve, linewidth=2.0, label=label)
        if not args.no_std_band and n_reps > 1:
            ax.fill_between(
                times_ref,
                mean_curve - std_curve,
                mean_curve + std_curve,
                alpha=0.2,
            )

    ax.set_title(args.title)
    ax.set_xlabel("t")
    ax.set_ylabel("<v(t)>")
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()

    if args.save is not None:
        out_path = args.save
        if not out_path.is_absolute():
            out_path = _PROJECT_ROOT / out_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=150)
        print(f"Saved figure: {out_path}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
